### ISSUE TITLE
Unable to find the save header in the target save.

### ISSUE THREAD

**Issue by GLOUPY-RnD** [Justin-Credible/hld-save-transfer#1]
Hi
I'd like to transfert my windows save file to a Mac save file (like you did) but have this issue : 

Error: Unable to find the save header in the target save.
    at main (/private/tmp/node_modules/hld-save-transfer/bin/hld-save-transfer.js:79:15)
    at Object.<anonymous> (/private/tmp/node_modules/hld-save-transfer/bin/hld-save-transfer.js:91:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

I started a new game on my Mac and waited for the save icon to appear before quitting the game and start the process so I don't understand why my Mac file doesn't have a header...

Thanks for your code anyway.

**Comment by GLOUPY-RnD** [comment]
I found the solution here : https://www.reddit.com/r/hyperlightdrifter/comments/4ctjpn/transferring_saves/?st=iwg7tste&sh=ecc5947d

Thing is, on my windows save file there is "eyAibWF..." but on the Mac file it's "eyAiYmF.."

I tried anyway as explained on reddit and it worked !

Cheers

**Comment by Justin-Credible** [comment]
Resolved in v1.0.1.

Thanks for the info!
